# Generated by Django 4.2.5 on 2023-10-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camara',
            name='cantidad_miembros',
        ),
        migrations.AddField(
            model_name='camara',
            name='integrantes',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
