# Generated by Django 4.2.5 on 2023-10-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0004_alter_integrantes_proyect_email_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
