# Generated by Django 4.2.5 on 2023-10-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0006_remove_avatar_imagen_alter_avatar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
