# Generated by Django 4.2.5 on 2023-10-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0007_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
